version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: next-seo
    versions:
    - 4.20.0
    - 4.22.0
    - 4.23.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: react-bootstrap
    versions:
    - 1.5.1
  - dependency-name: next-themes
    versions:
    - 0.0.12
